### ISSUE TITLE
Metode pengerjaan

### ISSUE THREAD

**Issue by wildanlsfs** [wildanlsfs/SIBengkel#1]
apakah dengan template Admin LTE sudah memenuhi kebutuhan atau tidak?

**Comment by mghazian** [comment]
Bisa jadi. Template apapun sebenarnya boleh digunakan selama hal-hal fungsional yang diperlukan bisa dilakukan

**Comment by wildanlsfs** [comment]
@mghazian mungkin kami akan membuatnya dengan menggunakan bootstrap... 
seperti template yang sudah saya unggah, index.html
