### ISSUE TITLE
Didalam bagian user kasir, terdapat tabel dan field apa saja?

### ISSUE THREAD

**Issue by mluqmanulhakimp** [wildanlsfs/SIBengkel#2]
@mghazian  
@irahumaira 
@mathovonic96

**Comment by mghazian** [comment]
Kasir memasukkan rekapitulasi transaksi hari itu:
- Pengeluaran
- Pemasukan

Yang dimaksud pengeluaran adalah bahan apa saja dan berapa yang habis digunakan pada hari itu (misal oli, bensin dll). Pemasukan adalah berapa omset dari transaksi

Kasir melakukan rekapitulasi di akhir shift. Pencatatan transaksi terjadi dua kali: satuan dan agregat. Pencatatan satuan dilakukan tiap kali ada transaksi. Pencatatan agregat dilakukan di akhir shift. Pencatatan satuan dilakukan secara manual (ditulis di buku), maka pencatatan satuan tidak perlu dimasukkan ke sistem
