### ISSUE TITLE
Apa yang bisa dilakukan admin terhadap akun admin lain

### ISSUE THREAD

**Issue by mghazian** [wildanlsfs/SIBengkel#4]
Aktifitas apa yang bisa dilakukan admin terhadap akun admin lain? (Insert/Update/Delete)

**Comment by wildanlsfs** [comment]
@mghazian ini pertanyaan untuk jodoh.in? atau sibengkel? ... kalau sibengkel, kita buat ada owner yang mendaftarkan kasir dan pastinya bisa crud kasir

**Comment by mghazian** [comment]
Buat jodoh.in
*salah git btw*
