### ISSUE TITLE
menyiapkan stock sm controlling stock

### ISSUE THREAD

**Issue by mluqmanulhakimp** [wildanlsfs/SIBengkel#5]
1. untuk usecase controlling stock dan menyiapkan stock, ini alurnya bagaimana?

**Comment by mghazian** [comment]
Manajemen tanpa menggunakan sistem membeli alat dan bahan yang diperlukan. Manajemen kemudian memasukkan stok ke gudang, baru setelah itu manajemen menginput barang apa saja yang dibeli.

Untuk kontroling, pemakaian stok digunakan saat montir bekerja. Setiap kali transaksi kasir harus memasukkan apa saja yang habis pakai.

Manajemen bisa melihat kapanpun jumlah stok yang dimiliki saat itu
