### ISSUE TITLE
Jadwal kerja 

### ISSUE THREAD

**Issue by herynugroho** [wildanlsfs/SIBengkel#6]
untuk jam kerja bengkel menggunakan jam kerja 08.00 - 16.00 atau 24 jam atau yg lainnya??
dan bagaimana dengan pembagian shift kerja pegawai??
- apakah shift hari?
atau shift jam?
atau yang lainnya
@mghazian

**Comment by mghazian** [comment]
Pegawai bekerja dengan shift harian
